name: Deploy my Angular App
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build angular app
        run: |
          echo "Install dependency"
          npm install
      - name: Deploy
        run: echo "Deploy to heroku"
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_TOKEN}}
          heroku_app_name: "blinis-web"
          heroku_email: "reyesbho@gmail.com"